# Generated by Django 4.2.25 on 2025-11-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='user',
            name='passw',
            field=models.TextField(max_length=100, null=True, verbose_name='Пароль'),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.TextField(blank='user', max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank='no bio yet', null=True, verbose_name='О себе'),
        ),
    ]
