# Generated by Django 4.2.25 on 2025-12-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_options_user_passw_user_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passw',
            new_name='password',
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(default='no bio yet', null=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(blank=True, max_length=30, verbose_name='Имя'),
        ),
    ]
